name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [ '8.3', '8.4', '8.5' ]

        steps:
            -   name: Set up PHP version ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2, php-cs-fixer

            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Get composer cache directory
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-${{ matrix.php }}-composer-

            -   name: Install dependencies
                run: |
                    composer install --prefer-dist --no-interaction --no-progress

            -   name: Lint
                if: ${{ success() }}
                run: |
                    composer ci:test:php:lint

            -   name: CGL
                if: ${{ success() }}
                run: |
                    composer ci:test:php:cgl

            -   name: PHPStan
                if: ${{ success() }}
                run: |
                    composer ci:test:php:phpstan -- --error-format=github

            -   name: Rector
                if: ${{ success() }}
                run: |
                    composer ci:test:php:rector

            -   name: Unit Tests
                if: ${{ success() }}
                run: |
                    composer ci:test:php:unit

            -   name: CPD
                if: ${{ success() }}
                run: composer ci:test:php:cpd
